export const LOGGED_IN 	= 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGGED_ERROR = 'LOGGED_ERROR';
export const LOGGED_DOING = 'LOGGED_DOING';

export const FETCH_VIDEO_DATA_LOADING = 'FETCH_VIDEO_DATA_LOADING'
export const FETCH_VIDEO_DATA_SUCCESS = 'FETCH_VIDEO_DATA_SUCCESS'
export const FETCH_VIDEO_DATA_ERROR = 'FETCH_VIDEO_DATA_ERROR'
export const FETCH_VIDEO_DETAIL_SUCCESS = 'FETCH_VIDEO_DETAIL_SUCCESS'

export const FETCH_CARTOON_DATA_LOADING = 'FETCH_CARTOON_DATA_LOADING'
export const FETCH_CARTOON_DATA_SUCCESS = 'FETCH_CARTOON_DATA_SUCCESS'
export const FETCH_CARTOON_DATA_ERROR = 'FETCH_CARTOON_DATA_ERROR'

export const FETCH_NOVEL_DATA_LOADING = 'FETCH_NOVEL_DATA_LOADING'
export const FETCH_NOVEL_DATA_SUCCESS = 'FETCH_NOVEL_DATA_SUCCESS'
export const FETCH_NOVEL_DATA_ERROR = 'FETCH_NOVEL_DATA_ERROR'

export const Router_Change = 'Router_Change'