export const LOGGED_IN 	= 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGGED_ERROR = 'LOGGED_ERROR';
export const LOGGED_DOING = 'LOGGED_DOING';

export const FETCH_VIDEO_DATA_LOADING = 'FETCH_VIDEO_DATA_LOADING'
export const FETCH_VIDEO_DATA_SUCCESS = 'FETCH_VIDEO_DATA_SUCCESS'
export const FETCH_VIDEO_DATA_ERROR = 'FETCH_VIDEO_DATA_ERROR'
export const FETCH_VIDEO_DETAIL_SUCCESS = 'FETCH_VIDEO_DETAIL_SUCCESS'
export const FETCH_VIDEO_DETAIL_CLEAR = 'FETCH_VIDEO_DETAIL_CLEAR'

export const FETCH_CARTOON_DATA_LOADING = 'FETCH_CARTOON_DATA_LOADING'
export const FETCH_CARTOON_DATA_SUCCESS = 'FETCH_CARTOON_DATA_SUCCESS'
export const FETCH_CARTOON_DATA_ERROR = 'FETCH_CARTOON_DATA_ERROR'
export const FETCH_CARTOON_DETAIL_SUCCESS = 'FETCH_CARTOON_DETAIL_SUCCESS'
export const FETCH_CARTOON_DETAIL_CLEAR = 'FETCH_CARTOON_DETAIL_CLEAR'

export const FETCH_NOVEL_DATA_LOADING = 'FETCH_NOVEL_DATA_LOADING'
export const FETCH_NOVEL_DATA_SUCCESS = 'FETCH_NOVEL_DATA_SUCCESS'
export const FETCH_NOVEL_DATA_ERROR = 'FETCH_NOVEL_DATA_ERROR'
export const FETCH_NOVEL_DETAIL_SUCCESS = 'FETCH_NOVEL_DETAIL_SUCCESS'
export const FETCH_NOVEL_DETAIL_CLEAR = 'FETCH_NOVEL_DETAIL_CLEAR'

export const FETCH_CHAPTER_DATA_LOADING = 'FETCH_CHAPTER_DATA_LOADING'
export const FETCH_CHAPTER_DATA_ERROR = 'FETCH_CHAPTER_DATA_ERROR'
export const FETCH_CARTOON_CHAPTER_SUCCESS = 'FETCH_CARTOON_CHAPTER_SUCCESS'
export const FETCH_NOVEL_CHAPTER_SUCCESS = 'FETCH_NOVEL_CHAPTER_SUCCESS'

export const FETCH_IMAGE_INDEX_LOADING = 'FETCH_IMAGE_INDEX_LOADING'
export const FETCH_IMAGE_INDEX_END = 'FETCH_IMAGE_INDEX_END'
export const FETCH_IMAGE_INDEX_SLIDER = 'FETCH_IMAGE_INDEX_SLIDER'
export const FETCH_IMAGE_INDEX_CLEAR = 'FETCH_IMAGE_INDEX_CLEAR'

export const Router_Change = 'Router_Change'